services:
  database:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    container_name: soat-database-dev
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-soat_dev}
      POSTGRES_USER: ${DATABASE_USER:-soat_user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-soat_password}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init.dev.sql:/docker-entrypoint-initdb.d/init.dev.sql
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${DATABASE_USER:-soat_user} -d ${DATABASE_NAME:-soat_dev}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
